# docker-compose.yaml
version: '3.8'

services:
  backend:
    build: ./
    container_name: chat-backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload